# Example: CompoundWiki

In [1]:
import os
import sys

project_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
src_path = os.path.join(project_root, "src")

if src_path not in sys.path:
    sys.path.insert(0, src_path)

print("PYTHONPATH:", sys.path[0])

PYTHONPATH: c:\Users\are10\Documents\BAFSTU\code\GitHub\pyBiodatafuse\src

In [2]:
# Import modules
import pandas as pd

from pyBiodatafuse import id_mapper
from pyBiodatafuse.annotators import intact, kegg, compoundwiki, pubchem, molmedb, opentargets
from pyBiodatafuse.graph import generator
from pyBiodatafuse.utils import combine_sources

# Load list of metabolites/chemicals/compounds

In [3]:
metabolites_of_interest = """15377
15361
15422
17234
16199
18211
57540
16865
15347
32952
35107
"""

metabolite_list = metabolites_of_interest.split("\n")
len(metabolite_list)

12

In [4]:
data_input = pd.DataFrame(metabolite_list, columns=["identifier"])
data_input.head()

  identifier
0      15377
1      15361
2      15422
3      17234
4      16199

### Entity resolution using BridgeDB

In [5]:
bridgedb_compound_df, bridgdb_metadata = id_mapper.bridgedb_xref(
    identifiers=data_input,
    input_species="Human",
    input_datasource="ChEBI",
    output_datasource="All",
)
bridgedb_compound_df.head(10)

  identifier identifier.source                       target    target.source
0      15377             ChEBI                       D00001        KEGG Drug
1      15377             ChEBI                  CHEBI:15377            ChEBI
2      15377             ChEBI                  HMDB0002111             HMDB
3      15377             ChEBI  XLYOFNOQVPJJNP-UHFFFAOYSA-N         InChIKey
4      15377             ChEBI                    HMDB02111             HMDB
5      15377             ChEBI                         Q283         Wikidata
6      15377             ChEBI                          937       ChemSpider
7      15377             ChEBI                      DB09145         DrugBank
8      15377             ChEBI                CHEMBL1098659  ChEMBL compound
9      15377             ChEBI                    7732-18-5              CAS

### Compound Interactions from IntAct

In [6]:
intact_compound_df, intact_compound_metadata = intact.get_compound_interactions(
    bridgedb_compound_df, interaction_type="both"
)
intact_compound_df.head(10)

Querying IntAct for compounds: 100%|██████████| 2/2 [00:09<00:00,  4.59s/it]
c:\Users\are10\Documents\BAFSTU\code\GitHub\pyBiodatafuse\src\pyBiodatafuse\annotators\intact.py:422: UserWarning: The intermediate_df in IntAct annotator should be checked, please create an issue on https://github.com/BioDataFuse/pyBiodatafuse/issues/.
  give_annotator_warning(Cons.INTACT)

,identifier,identifier.source,target,target.source,IntAct_compound_interactions
0,15377,ChEBI,CHEBI:15377,ChEBI,"[{'interaction_id': nan, 'interactor_id_A': na..."
1,15361,ChEBI,CHEBI:15361,ChEBI,"[{'interaction_id': 'EBI-6621805', 'interactor..."
2,15422,ChEBI,CHEBI:15422,ChEBI,"[{'interaction_id': 'EBI-25463622', 'interacto..."
3,17234,ChEBI,CHEBI:17234,ChEBI,"[{'interaction_id': nan, 'interactor_id_A': na..."
4,16199,ChEBI,CHEBI:16199,ChEBI,"[{'interaction_id': nan, 'interactor_id_A': na..."
5,18211,ChEBI,CHEBI:18211,ChEBI,"[{'interaction_id': nan, 'interactor_id_A': na..."
6,57540,ChEBI,CHEBI:57540,ChEBI,"[{'interaction_id': nan, 'interactor_id_A': na..."
7,16865,ChEBI,CHEBI:16865,ChEBI,"[{'interaction_id': nan, 'interactor_id_A': na..."
8,15347,ChEBI,CHEBI:15347,ChEBI,"[{'interaction_id': nan, 'interactor_id_A': na..."
9,32952,ChEBI,CHEBI:32952,ChEBI,"[{'interaction_id': nan, 'interactor_id_A': na..."

In [7]:
intact_compound_df["IntAct_compound_interactions"][0]

[{'interaction_id': nan,
  'interactor_id_A': nan,
  'interactor_id_B': nan,
  'score': nan,
  'biological_role_A': nan,
  'biological_role_B': nan,
  'type': nan,
  'detection_method': nan,
  'host_organism': nan,
  'interactor_A_name': nan,
  'interactor_B_name': nan,
  'interactor_A_species': nan,
  'interactor_B_species': nan,
  'molecule_A': nan,
  'molecule_B': nan,
  'id_A': nan,
  'id_B': nan,
  'pubmed_publication_id': nan,
  'intact_link_to': nan}]

## MolMeDB

In [8]:
molmedb_df, molmedb_metadata = molmedb.get_compound_gene_inhibitor(bridgedb_compound_df)
molmedb_df.head()

,identifier,identifier.source,target,target.source,MolMeDB_transporter_inhibited
0,15347,ChEBI,CSCPPACGZOOCGX-UHFFFAOYSA-N,InChIKey,"[{'MolMeDB_uniprot_trembl_id': nan, 'MolMeDB_h..."
1,15361,ChEBI,LCTONWCANYUPML-UHFFFAOYSA-M,InChIKey,"[{'MolMeDB_uniprot_trembl_id': nan, 'MolMeDB_h..."
2,15377,ChEBI,XLYOFNOQVPJJNP-UHFFFAOYSA-N,InChIKey,"[{'MolMeDB_uniprot_trembl_id': nan, 'MolMeDB_h..."
3,15422,ChEBI,ZKHQWZAMYRWXGA-KQYNXXCUSA-N,InChIKey,"[{'MolMeDB_uniprot_trembl_id': nan, 'MolMeDB_h..."
4,16199,ChEBI,XSQUKJJJFZCRTK-UHFFFAOYSA-N,InChIKey,"[{'MolMeDB_uniprot_trembl_id': nan, 'MolMeDB_h..."

In [9]:
molmedb_df["MolMeDB_transporter_inhibited"][5]

[{'MolMeDB_uniprot_trembl_id': 'Uniprot-TrEMBL:P48066',
  'MolMeDB_hgnc_symbol': 'SLC6A11',
  'source_pmid': '8057281'}]

In [10]:
combined_df = combine_sources(
    bridgedb_compound_df,
    [
        intact_compound_df, 
    ],
)

In [11]:
combined_df.head()

,identifier,identifier.source,target,target.source,IntAct_compound_interactions
0,15377,ChEBI,962,PubChem Compound,"[{'interaction_id': nan, 'interactor_id_A': na..."
1,15361,ChEBI,107735,PubChem Compound,"[{'interaction_id': 'EBI-6621805', 'interactor..."
2,15422,ChEBI,5957,PubChem Compound,"[{'interaction_id': 'EBI-25463622', 'interacto..."
3,16199,ChEBI,1176,PubChem Compound,"[{'interaction_id': nan, 'interactor_id_A': na..."
4,18211,ChEBI,833,PubChem Compound,"[{'interaction_id': nan, 'interactor_id_A': na..."

In [12]:
combined_df, compoundwiki_metadata = compoundwiki.get_compound_annotations(combined_df)

b
Processing IntAct column for compounds: IntAct_compound_interactions

In [13]:
combined_df.head()

,identifier,identifier.source,target,target.source,IntAct_compound_interactions,CompoundWiki_compounds
0,15377,ChEBI,962,PubChem Compound,"[{'interaction_id': nan, 'interactor_id_A': na...","[{'CAS Registry Number': nan, 'ChEBI ID': nan,..."
1,15361,ChEBI,107735,PubChem Compound,"[{'interaction_id': 'EBI-6621805', 'interactor...","[{'CAS Registry Number': nan, 'ChEBI ID': nan,..."
2,15422,ChEBI,5957,PubChem Compound,"[{'interaction_id': 'EBI-25463622', 'interacto...","[{'CAS Registry Number': '56-65-5', 'ChEBI ID'..."
3,16199,ChEBI,1176,PubChem Compound,"[{'interaction_id': nan, 'interactor_id_A': na...","[{'CAS Registry Number': nan, 'ChEBI ID': nan,..."
4,18211,ChEBI,833,PubChem Compound,"[{'interaction_id': nan, 'interactor_id_A': na...","[{'CAS Registry Number': nan, 'ChEBI ID': nan,..."

In [14]:
combined_df['IntAct_compound_interactions'][2]

[{'interaction_id': 'EBI-25463622',
  'interactor_id_A': 'EBI-1108845',
  'interactor_id_B': 'EBI-1108845',
  'score': 0.71,
  'biological_role_A': 'unspecified role',
  'biological_role_B': 'competitor',
  'type': 'direct interaction',
  'detection_method': 'crosslink',
  'host_organism': 'Escherichia coli (strain K12)',
  'interactor_A_name': 'atp',
  'interactor_B_name': 'atp',
  'interactor_A_species': 'Chemical synthesis (Chemical synthesis)',
  'interactor_B_species': 'Chemical synthesis (Chemical synthesis)',
  'molecule_A': 'atp',
  'molecule_B': 'atp',
  'id_A': 'CHEBI:15422',
  'id_B': 'CHEBI:15422',
  'pubmed_publication_id': '10048040',
  'intact_link_to': '15422',
  'CompoundWiki_compounds': [{'CAS Registry Number': '56-65-5',
    'ChEBI ID': '15422',
    'ChEMBL ID': 'CHEMBL14249',
    'CosIng number': '31370',
    'DSSTOX compound identifier': 'DTXCID302559',
    'EC number': '200-283-2',
    'ECHA Substance Infocard ID': '100.000.258',
    'InChI': 'InChI=1S/C10H16N5O13P3/c11-8-5-9(13-2-12-8)15(3-14-5)10-7(17)6(16)4(26-10)1-25-30(21,22)28-31(23,24)27-29(18,19)20/h2-4,6-7,10,16-17H,1H2,(H,21,22)(H,23,24)(H2,11,12,13)(H2,18,19,20)/t4-,6-,7-,10-/m1/s1',
    'InChIKey': 'ZKHQWZAMYRWXGA-KQYNXXCUSA-N',
    'KEGG ID': 'D08646',
    'PubChem CID': '5957',
    'SMILES': 'C1=NC2=C(C(=N1)N)N=CN2[C@H]3[C@@H]([C@@H]([C@H](O3)COP(=O)(O)OP(=O)(O)OP(=O)(O)O)O)O',
    'Wikidata Q identifier': 'Q80863',
    'chemical formula': 'C₁₀H₁₆N₅O₁₃P₃',
    'instance of': 'organophosphates',
    'mass': '507.1815',
    'xenobiotic metabolism pathway': 'WP521',
    'compound label': 'adenosine triphosphate',
    'input_identifier': 'CHEBI:15422'}]},
 {'interaction_id': 'EBI-26605262',
  'interactor_id_A': 'EBI-1108845',
  'interactor_id_B': 'EBI-1108845',
  'score': 0.71,
  'biological_role_A': 'unspecified role',
  'biological_role_B': 'stimulator',
  'type': 'direct interaction',
  'detection_method': 'light microscopy',
  'host_organism': 'In vitro',
  'interactor_A_name': 'atp',
  'interactor_B_name': 'atp',
  'interactor_A_species': 'Chemical synthesis (Chemical synthesis)',
  'interactor_B_species': 'Chemical synthesis (Chemical synthesis)',
  'molecule_A': 'atp',
  'molecule_B': 'atp',
  'id_A': 'CHEBI:15422',
  'id_B': 'CHEBI:15422',
  'pubmed_publication_id': '33477032',
  'intact_link_to': '15422',
  'CompoundWiki_compounds': [{'CAS Registry Number': '56-65-5',
    'ChEBI ID': '15422',
    'ChEMBL ID': 'CHEMBL14249',
    'CosIng number': '31370',
    'DSSTOX compound identifier': 'DTXCID302559',
    'EC number': '200-283-2',
    'ECHA Substance Infocard ID': '100.000.258',
    'InChI': 'InChI=1S/C10H16N5O13P3/c11-8-5-9(13-2-12-8)15(3-14-5)10-7(17)6(16)4(26-10)1-25-30(21,22)28-31(23,24)27-29(18,19)20/h2-4,6-7,10,16-17H,1H2,(H,21,22)(H,23,24)(H2,11,12,13)(H2,18,19,20)/t4-,6-,7-,10-/m1/s1',
    'InChIKey': 'ZKHQWZAMYRWXGA-KQYNXXCUSA-N',
    'KEGG ID': 'D08646',
    'PubChem CID': '5957',
    'SMILES': 'C1=NC2=C(C(=N1)N)N=CN2[C@H]3[C@@H]([C@@H]([C@H](O3)COP(=O)(O)OP(=O)(O)OP(=O)(O)O)O)O',
    'Wikidata Q identifier': 'Q80863',
    'chemical formula': 'C₁₀H₁₆N₅O₁₃P₃',
    'instance of': 'organophosphates',
    'mass': '507.1815',
    'xenobiotic metabolism pathway': 'WP521',
    'compound label': 'adenosine triphosphate',
    'input_identifier': 'CHEBI:15422'}]},
 {'interaction_id': 'EBI-9007503',
  'interactor_id_A': 'EBI-1108845',
  'interactor_id_B': 'EBI-1108845',
  'score': 0.71,
  'biological_role_A': 'unspecified role',
  'biological_role_B': 'competitor',
  'type': 'direct interaction',
  'detection_method': 'crosslink',
  'host_organism': 'In vitro',
  'interactor_A_name': 'atp',
  'interactor_B_name': 'atp',
  'interactor_A_species': 'Chemical synthesis (Chemical synthesis)',
  'interactor_B_species': 'Chemical synthesis (Chemical synthesis)',
  'molecule_A': 'atp',
  'molecule_B': 'atp',
  'id_A': 'CHEBI:15422',
  'id_B': 'CHEBI:15422',
  'pubmed_publication_id': '22331906',
  'intact_link_to': '15422',
  'CompoundWiki_compounds': [{'CAS Registry Number': '56-65-5',
    'ChEBI ID': '15422',
    'ChEMBL ID': 'CHEMBL14249',
    'CosIng number': '31370',
    'DSSTOX compound identifier': 'DTXCID302559',
    'EC number': '200-283-2',
    'ECHA Substance Infocard ID': '100.000.258',
    'InChI': 'InChI=1S/C10H16N5O13P3/c11-8-5-9(13-2-12-8)15(3-14-5)10-7(17)6(16)4(26-10)1-25-30(21,22)28-31(23,24)27-29(18,19)20/h2-4,6-7,10,16-17H,1H2,(H,21,22)(H,23,24)(H2,11,12,13)(H2,18,19,20)/t4-,6-,7-,10-/m1/s1',
    'InChIKey': 'ZKHQWZAMYRWXGA-KQYNXXCUSA-N',
    'KEGG ID': 'D08646',
    'PubChem CID': '5957',
    'SMILES': 'C1=NC2=C(C(=N1)N)N=CN2[C@H]3[C@@H]([C@@H]([C@H](O3)COP(=O)(O)OP(=O)(O)OP(=O)(O)O)O)O',
    'Wikidata Q identifier': 'Q80863',
    'chemical formula': 'C₁₀H₁₆N₅O₁₃P₃',
    'instance of': 'organophosphates',
    'mass': '507.1815',
    'xenobiotic metabolism pathway': 'WP521',
    'compound label': 'adenosine triphosphate',
    'input_identifier': 'CHEBI:15422'}]},
 {'interaction_id': 'EBI-2908676',
  'interactor_id_A': 'EBI-2607221',
  'interactor_id_B': 'EBI-1108845',
  'score': 0.44,
  'biological_role_A': 'enzyme',
  'biological_role_B': 'enzyme target',
  'type': 'atpase reaction',
  'detection_method': 'atpase assay',
  'host_organism': 'In vitro',
  'interactor_A_name': 'o42263_xenla',
  'interactor_B_name': 'atp',
  'interactor_A_species': 'Xenopus laevis (African clawed frog)',
  'interactor_B_species': 'Chemical synthesis (Chemical synthesis)',
  'molecule_A': 'XCENP-E',
  'molecule_B': 'atp',
  'id_A': 'uniprotkb:O42263',
  'id_B': 'CHEBI:15422',
  'pubmed_publication_id': '20691903',
  'intact_link_to': 'EBI-2607221',
  'CompoundWiki_compounds': [{'CAS Registry Number': '56-65-5',
    'ChEBI ID': '15422',
    'ChEMBL ID': 'CHEMBL14249',
    'CosIng number': '31370',
    'DSSTOX compound identifier': 'DTXCID302559',
    'EC number': '200-283-2',
    'ECHA Substance Infocard ID': '100.000.258',
    'InChI': 'InChI=1S/C10H16N5O13P3/c11-8-5-9(13-2-12-8)15(3-14-5)10-7(17)6(16)4(26-10)1-25-30(21,22)28-31(23,24)27-29(18,19)20/h2-4,6-7,10,16-17H,1H2,(H,21,22)(H,23,24)(H2,11,12,13)(H2,18,19,20)/t4-,6-,7-,10-/m1/s1',
    'InChIKey': 'ZKHQWZAMYRWXGA-KQYNXXCUSA-N',
    'KEGG ID': 'D08646',
    'PubChem CID': '5957',
    'SMILES': 'C1=NC2=C(C(=N1)N)N=CN2[C@H]3[C@@H]([C@@H]([C@H](O3)COP(=O)(O)OP(=O)(O)OP(=O)(O)O)O)O',
    'Wikidata Q identifier': 'Q80863',
    'chemical formula': 'C₁₀H₁₆N₅O₁₃P₃',
    'instance of': 'organophosphates',
    'mass': '507.1815',
    'xenobiotic metabolism pathway': 'WP521',
    'compound label': 'adenosine triphosphate',
    'input_identifier': 'CHEBI:15422'}]},
 {'interaction_id': 'EBI-2213775',
  'interactor_id_A': 'EBI-1108845',
  'interactor_id_B': 'EBI-2213586',
  'score': 0.4,
  'biological_role_A': 'unspecified role',
  'biological_role_B': 'unspecified role',
  'type': 'physical association',
  'detection_method': 'comig non denat gel',
  'host_organism': 'In vitro',
  'interactor_A_name': 'atp',
  'interactor_B_name': 'muke_haedu',
  'interactor_A_species': 'Chemical synthesis (Chemical synthesis)',
  'interactor_B_species': 'Haemophilus ducreyi (strain 35000HP / ATCC 700724)',
  'molecule_A': 'atp',
  'molecule_B': 'mukE',
  'id_A': 'CHEBI:15422',
  'id_B': 'uniprotkb:Q7VL95',
  'pubmed_publication_id': '19135891',
  'intact_link_to': 'EBI-2213586',
  'CompoundWiki_compounds': [{'CAS Registry Number': '56-65-5',
    'ChEBI ID': '15422',
    'ChEMBL ID': 'CHEMBL14249',
    'CosIng number': '31370',
    'DSSTOX compound identifier': 'DTXCID302559',
    'EC number': '200-283-2',
    'ECHA Substance Infocard ID': '100.000.258',
    'InChI': 'InChI=1S/C10H16N5O13P3/c11-8-5-9(13-2-12-8)15(3-14-5)10-7(17)6(16)4(26-10)1-25-30(21,22)28-31(23,24)27-29(18,19)20/h2-4,6-7,10,16-17H,1H2,(H,21,22)(H,23,24)(H2,11,12,13)(H2,18,19,20)/t4-,6-,7-,10-/m1/s1',
    'InChIKey': 'ZKHQWZAMYRWXGA-KQYNXXCUSA-N',
    'KEGG ID': 'D08646',
    'PubChem CID': '5957',
    'SMILES': 'C1=NC2=C(C(=N1)N)N=CN2[C@H]3[C@@H]([C@@H]([C@H](O3)COP(=O)(O)OP(=O)(O)OP(=O)(O)O)O)O',
    'Wikidata Q identifier': 'Q80863',
    'chemical formula': 'C₁₀H₁₆N₅O₁₃P₃',
    'instance of': 'organophosphates',
    'mass': '507.1815',
    'xenobiotic metabolism pathway': 'WP521',
    'compound label': 'adenosine triphosphate',
    'input_identifier': 'CHEBI:15422'}]},
 {'interaction_id': 'EBI-2120618',
  'interactor_id_A': 'EBI-2120435',
  'interactor_id_B': 'EBI-1108845',
  'score': 0.44,
  'biological_role_A': 'unspecified role',
  'biological_role_B': 'unspecified role',
  'type': 'direct interaction',
  'detection_method': 'fps',
  'host_organism': 'In vitro',
  'interactor_A_name': 'o67056_aquae',
  'interactor_B_name': 'atp',
  'interactor_A_species': 'Aquifex aeolicus (strain VF5)',
  'interactor_B_species': 'Chemical synthesis (Chemical synthesis)',
  'molecule_A': 'dnaC',
  'molecule_B': 'atp',
  'id_A': 'uniprotkb:O67056',
  'id_B': 'CHEBI:15422',
  'pubmed_publication_id': '19013274',
  'intact_link_to': 'EBI-2120435',
  'CompoundWiki_compounds': [{'CAS Registry Number': '56-65-5',
    'ChEBI ID': '15422',
    'ChEMBL ID': 'CHEMBL14249',
    'CosIng number': '31370',
    'DSSTOX compound identifier': 'DTXCID302559',
    'EC number': '200-283-2',
    'ECHA Substance Infocard ID': '100.000.258',
    'InChI': 'InChI=1S/C10H16N5O13P3/c11-8-5-9(13-2-12-8)15(3-14-5)10-7(17)6(16)4(26-10)1-25-30(21,22)28-31(23,24)27-29(18,19)20/h2-4,6-7,10,16-17H,1H2,(H,21,22)(H,23,24)(H2,11,12,13)(H2,18,19,20)/t4-,6-,7-,10-/m1/s1',
    'InChIKey': 'ZKHQWZAMYRWXGA-KQYNXXCUSA-N',
    'KEGG ID': 'D08646',
    'PubChem CID': '5957',
    'SMILES': 'C1=NC2=C(C(=N1)N)N=CN2[C@H]3[C@@H]([C@@H]([C@H](O3)COP(=O)(O)OP(=O)(O)OP(=O)(O)O)O)O',
    'Wikidata Q identifier': 'Q80863',
    'chemical formula': 'C₁₀H₁₆N₅O₁₃P₃',
    'instance of': 'organophosphates',
    'mass': '507.1815',
    'xenobiotic metabolism pathway': 'WP521',
    'compound label': 'adenosine triphosphate',
    'input_identifier': 'CHEBI:15422'}]},
 {'interaction_id': 'EBI-25425402',
  'interactor_id_A': 'EBI-10963472',
  'interactor_id_B': 'EBI-1108845',
  'score': 0.44,
  'biological_role_A': 'enzyme',
  'biological_role_B': 'enzyme target',
  'type': 'atpase reaction',
  'detection_method': 'atpase assay',
  'host_organism': 'In vitro',
  'interactor_A_name': 'o00159-2',
  'interactor_B_name': 'atp',
  'interactor_A_species': 'Homo sapiens',
  'interactor_B_species': 'Chemical synthesis (Chemical synthesis)',
  'molecule_A': 'MYO1C',
  'molecule_B': 'atp',
  'id_A': 'uniprotkb:O00159-2',
  'id_B': 'CHEBI:15422',
  'pubmed_publication_id': '24636949',
  'intact_link_to': 'EBI-10963472',
  'CompoundWiki_compounds': [{'CAS Registry Number': '56-65-5',
    'ChEBI ID': '15422',
    'ChEMBL ID': 'CHEMBL14249',
    'CosIng number': '31370',
    'DSSTOX compound identifier': 'DTXCID302559',
    'EC number': '200-283-2',
    'ECHA Substance Infocard ID': '100.000.258',
    'InChI': 'InChI=1S/C10H16N5O13P3/c11-8-5-9(13-2-12-8)15(3-14-5)10-7(17)6(16)4(26-10)1-25-30(21,22)28-31(23,24)27-29(18,19)20/h2-4,6-7,10,16-17H,1H2,(H,21,22)(H,23,24)(H2,11,12,13)(H2,18,19,20)/t4-,6-,7-,10-/m1/s1',
    'InChIKey': 'ZKHQWZAMYRWXGA-KQYNXXCUSA-N',
    'KEGG ID': 'D08646',
    'PubChem CID': '5957',
    'SMILES': 'C1=NC2=C(C(=N1)N)N=CN2[C@H]3[C@@H]([C@@H]([C@H](O3)COP(=O)(O)OP(=O)(O)OP(=O)(O)O)O)O',
    'Wikidata Q identifier': 'Q80863',
    'chemical formula': 'C₁₀H₁₆N₅O₁₃P₃',
    'instance of': 'organophosphates',
    'mass': '507.1815',
    'xenobiotic metabolism pathway': 'WP521',
    'compound label': 'adenosine triphosphate',
    'input_identifier': 'CHEBI:15422'}]},
 {'interaction_id': 'EBI-25425498',
  'interactor_id_A': 'EBI-10963472',
  'interactor_id_B': 'EBI-1108845',
  'score': 0.44,
  'biological_role_A': 'enzyme',
  'biological_role_B': 'enzyme target',
  'type': 'atpase reaction',
  'detection_method': 'atpase assay',
  'host_organism': 'In vitro',
  'interactor_A_name': 'o00159-2',
  'interactor_B_name': 'atp',
  'interactor_A_species': 'Homo sapiens',
  'interactor_B_species': 'Chemical synthesis (Chemical synthesis)',
  'molecule_A': 'MYO1C',
  'molecule_B': 'atp',
  'id_A': 'uniprotkb:O00159-2',
  'id_B': 'CHEBI:15422',
  'pubmed_publication_id': '24636949',
  'intact_link_to': 'EBI-10963472',
  'CompoundWiki_compounds': [{'CAS Registry Number': '56-65-5',
    'ChEBI ID': '15422',
    'ChEMBL ID': 'CHEMBL14249',
    'CosIng number': '31370',
    'DSSTOX compound identifier': 'DTXCID302559',
    'EC number': '200-283-2',
    'ECHA Substance Infocard ID': '100.000.258',
    'InChI': 'InChI=1S/C10H16N5O13P3/c11-8-5-9(13-2-12-8)15(3-14-5)10-7(17)6(16)4(26-10)1-25-30(21,22)28-31(23,24)27-29(18,19)20/h2-4,6-7,10,16-17H,1H2,(H,21,22)(H,23,24)(H2,11,12,13)(H2,18,19,20)/t4-,6-,7-,10-/m1/s1',
    'InChIKey': 'ZKHQWZAMYRWXGA-KQYNXXCUSA-N',
    'KEGG ID': 'D08646',
    'PubChem CID': '5957',
    'SMILES': 'C1=NC2=C(C(=N1)N)N=CN2[C@H]3[C@@H]([C@@H]([C@H](O3)COP(=O)(O)OP(=O)(O)OP(=O)(O)O)O)O',
    'Wikidata Q identifier': 'Q80863',
    'chemical formula': 'C₁₀H₁₆N₅O₁₃P₃',
    'instance of': 'organophosphates',
    'mass': '507.1815',
    'xenobiotic metabolism pathway': 'WP521',
    'compound label': 'adenosine triphosphate',
    'input_identifier': 'CHEBI:15422'}]},
 {'interaction_id': 'EBI-3649155',
  'interactor_id_A': 'EBI-29732',
  'interactor_id_B': 'EBI-1108845',
  'score': 0.54,
  'biological_role_A': 'unspecified role',
  'biological_role_B': 'unspecified role',
  'type': 'direct interaction',
  'detection_method': 'chromatography',
  'host_organism': 'In vitro',
  'interactor_A_name': 'clp1_yeast',
  'interactor_B_name': 'atp',
  'interactor_A_species': 'Saccharomyces cerevisiae',
  'interactor_B_species': 'Chemical synthesis (Chemical synthesis)',
  'molecule_A': 'CLP1',
  'molecule_B': 'atp',
  'id_A': 'uniprotkb:Q08685',
  'id_B': 'CHEBI:15422',
  'pubmed_publication_id': '17151076',
  'intact_link_to': 'EBI-29732',
  'CompoundWiki_compounds': [{'CAS Registry Number': '56-65-5',
    'ChEBI ID': '15422',
    'ChEMBL ID': 'CHEMBL14249',
    'CosIng number': '31370',
    'DSSTOX compound identifier': 'DTXCID302559',
    'EC number': '200-283-2',
    'ECHA Substance Infocard ID': '100.000.258',
    'InChI': 'InChI=1S/C10H16N5O13P3/c11-8-5-9(13-2-12-8)15(3-14-5)10-7(17)6(16)4(26-10)1-25-30(21,22)28-31(23,24)27-29(18,19)20/h2-4,6-7,10,16-17H,1H2,(H,21,22)(H,23,24)(H2,11,12,13)(H2,18,19,20)/t4-,6-,7-,10-/m1/s1',
    'InChIKey': 'ZKHQWZAMYRWXGA-KQYNXXCUSA-N',
    'KEGG ID': 'D08646',
    'PubChem CID': '5957',
    'SMILES': 'C1=NC2=C(C(=N1)N)N=CN2[C@H]3[C@@H]([C@@H]([C@H](O3)COP(=O)(O)OP(=O)(O)OP(=O)(O)O)O)O',
    'Wikidata Q identifier': 'Q80863',
    'chemical formula': 'C₁₀H₁₆N₅O₁₃P₃',
    'instance of': 'organophosphates',
    'mass': '507.1815',
    'xenobiotic metabolism pathway': 'WP521',
    'compound label': 'adenosine triphosphate',
    'input_identifier': 'CHEBI:15422'}]},
 {'interaction_id': 'EBI-3650828',
  'interactor_id_A': 'EBI-1108845',
  'interactor_id_B': 'EBI-29732',
  'score': 0.54,
  'biological_role_A': 'unspecified role',
  'biological_role_B': 'unspecified role',
  'type': 'physical association',
  'detection_method': 'chromatography',
  'host_organism': 'In vitro',
  'interactor_A_name': 'atp',
  'interactor_B_name': 'clp1_yeast',
  'interactor_A_species': 'Chemical synthesis (Chemical synthesis)',
  'interactor_B_species': 'Saccharomyces cerevisiae',
  'molecule_A': 'atp',
  'molecule_B': 'CLP1',
  'id_A': 'CHEBI:15422',
  'id_B': 'uniprotkb:Q08685',
  'pubmed_publication_id': '17151076',
  'intact_link_to': 'EBI-29732',
  'CompoundWiki_compounds': [{'CAS Registry Number': '56-65-5',
    'ChEBI ID': '15422',
    'ChEMBL ID': 'CHEMBL14249',
    'CosIng number': '31370',
    'DSSTOX compound identifier': 'DTXCID302559',
    'EC number': '200-283-2',
    'ECHA Substance Infocard ID': '100.000.258',
    'InChI': 'InChI=1S/C10H16N5O13P3/c11-8-5-9(13-2-12-8)15(3-14-5)10-7(17)6(16)4(26-10)1-25-30(21,22)28-31(23,24)27-29(18,19)20/h2-4,6-7,10,16-17H,1H2,(H,21,22)(H,23,24)(H2,11,12,13)(H2,18,19,20)/t4-,6-,7-,10-/m1/s1',
    'InChIKey': 'ZKHQWZAMYRWXGA-KQYNXXCUSA-N',
    'KEGG ID': 'D08646',
    'PubChem CID': '5957',
    'SMILES': 'C1=NC2=C(C(=N1)N)N=CN2[C@H]3[C@@H]([C@@H]([C@H](O3)COP(=O)(O)OP(=O)(O)OP(=O)(O)O)O)O',
    'Wikidata Q identifier': 'Q80863',
    'chemical formula': 'C₁₀H₁₆N₅O₁₃P₃',
    'instance of': 'organophosphates',
    'mass': '507.1815',
    'xenobiotic metabolism pathway': 'WP521',
    'compound label': 'adenosine triphosphate',
    'input_identifier': 'CHEBI:15422'}]},
 {'interaction_id': 'EBI-8769124',
  'interactor_id_A': 'EBI-1108845',
  'interactor_id_B': 'EBI-8769114',
  'score': 0.32,
  'biological_role_A': 'unspecified role',
  'biological_role_B': 'unspecified role',
  'type': 'physical association',
  'detection_method': 'electron microscopy',
  'host_organism': 'In vitro',
  'interactor_A_name': 'atp',
  'interactor_B_name': 'rlp_rhort',
  'interactor_A_species': 'Chemical synthesis (Chemical synthesis)',
  'interactor_B_species': 'Rhodospirillum rubrum (strain ATCC 11170 / NCIB 8255)',
  'molecule_A': 'atp',
  'molecule_B': 'rlp',
  'id_A': 'CHEBI:15422',
  'id_B': 'uniprotkb:Q2RSU7',
  'pubmed_publication_id': '23746846',
  'intact_link_to': 'EBI-8769114',
  'CompoundWiki_compounds': [{'CAS Registry Number': '56-65-5',
    'ChEBI ID': '15422',
    'ChEMBL ID': 'CHEMBL14249',
    'CosIng number': '31370',
    'DSSTOX compound identifier': 'DTXCID302559',
    'EC number': '200-283-2',
    'ECHA Substance Infocard ID': '100.000.258',
    'InChI': 'InChI=1S/C10H16N5O13P3/c11-8-5-9(13-2-12-8)15(3-14-5)10-7(17)6(16)4(26-10)1-25-30(21,22)28-31(23,24)27-29(18,19)20/h2-4,6-7,10,16-17H,1H2,(H,21,22)(H,23,24)(H2,11,12,13)(H2,18,19,20)/t4-,6-,7-,10-/m1/s1',
    'InChIKey': 'ZKHQWZAMYRWXGA-KQYNXXCUSA-N',
    'KEGG ID': 'D08646',
    'PubChem CID': '5957',
    'SMILES': 'C1=NC2=C(C(=N1)N)N=CN2[C@H]3[C@@H]([C@@H]([C@H](O3)COP(=O)(O)OP(=O)(O)OP(=O)(O)O)O)O',
    'Wikidata Q identifier': 'Q80863',
    'chemical formula': 'C₁₀H₁₆N₅O₁₃P₃',
    'instance of': 'organophosphates',
    'mass': '507.1815',
    'xenobiotic metabolism pathway': 'WP521',
    'compound label': 'adenosine triphosphate',
    'input_identifier': 'CHEBI:15422'}]},
 {'interaction_id': 'EBI-12518595',
  'interactor_id_A': 'EBI-23112',
  'interactor_id_B': 'EBI-1108845',
  'score': 0.44,
  'biological_role_A': 'enzyme',
  'biological_role_B': 'unspecified role',
  'type': 'enzymatic reaction',
  'detection_method': 'enzymatic study',
  'host_organism': 'In vitro',
  'interactor_A_name': 'thg1_yeast',
  'interactor_B_name': 'atp',
  'interactor_A_species': 'Saccharomyces cerevisiae',
  'interactor_B_species': 'Chemical synthesis (Chemical synthesis)',
  'molecule_A': 'THG1',
  'molecule_B': 'atp',
  'id_A': 'uniprotkb:P53215',
  'id_B': 'CHEBI:15422',
  'pubmed_publication_id': '14633974',
  'intact_link_to': 'EBI-23112',
  'CompoundWiki_compounds': [{'CAS Registry Number': '56-65-5',
    'ChEBI ID': '15422',
    'ChEMBL ID': 'CHEMBL14249',
    'CosIng number': '31370',
    'DSSTOX compound identifier': 'DTXCID302559',
    'EC number': '200-283-2',
    'ECHA Substance Infocard ID': '100.000.258',
    'InChI': 'InChI=1S/C10H16N5O13P3/c11-8-5-9(13-2-12-8)15(3-14-5)10-7(17)6(16)4(26-10)1-25-30(21,22)28-31(23,24)27-29(18,19)20/h2-4,6-7,10,16-17H,1H2,(H,21,22)(H,23,24)(H2,11,12,13)(H2,18,19,20)/t4-,6-,7-,10-/m1/s1',
    'InChIKey': 'ZKHQWZAMYRWXGA-KQYNXXCUSA-N',
    'KEGG ID': 'D08646',
    'PubChem CID': '5957',
    'SMILES': 'C1=NC2=C(C(=N1)N)N=CN2[C@H]3[C@@H]([C@@H]([C@H](O3)COP(=O)(O)OP(=O)(O)OP(=O)(O)O)O)O',
    'Wikidata Q identifier': 'Q80863',
    'chemical formula': 'C₁₀H₁₆N₅O₁₃P₃',
    'instance of': 'organophosphates',
    'mass': '507.1815',
    'xenobiotic metabolism pathway': 'WP521',
    'compound label': 'adenosine triphosphate',
    'input_identifier': 'CHEBI:15422'}]},
 {'interaction_id': 'EBI-12560232',
  'interactor_id_A': 'EBI-23112',
  'interactor_id_B': 'EBI-1108845',
  'score': 0.44,

In [15]:
pygraph = generator.build_networkx_graph(combined_df)

Building graph: 100%|██████████| 8/8 [00:00<00:00, 172.51it/s]

In [16]:
print(pygraph)

MultiDiGraph with 86 nodes and 79 edges

In [17]:
from pyBiodatafuse.graph import cytoscape

cytoscape.load_graph(pygraph, network_name="Test network")

Applying default style...
Applying preferred layout

# Load list of genes

In [18]:
genes_of_interest = """KCNJ5
SLC25A1"""

gene_list = genes_of_interest.split("\n")
len(gene_list)

2

In [19]:
data_input = pd.DataFrame(gene_list, columns=["identifier"])
data_input.head()

input_species = "Human"

bridgedb_df, bridgedb_metadata = id_mapper.bridgedb_xref(
    identifiers=data_input,
    input_species=input_species,
    input_datasource="HGNC",
    output_datasource="All",
)

bridgedb_df.head(25)

   identifier identifier.source          target          target.source
0       KCNJ5              HGNC         3355874                   Affy
1       KCNJ5              HGNC         3355873                   Affy
2       KCNJ5              HGNC         3355871                   Affy
3       KCNJ5              HGNC      GO:0086091          Gene Ontology
4       KCNJ5              HGNC       HGNC:6266  HGNC Accession Number
5       KCNJ5              HGNC         3355877                   Affy
6       KCNJ5              HGNC      GO:0006813          Gene Ontology
7       KCNJ5              HGNC      GO:0016021          Gene Ontology
8       KCNJ5              HGNC      uc001qet.5    UCSC Genome Browser
9       KCNJ5              HGNC  208397_PM_x_at                   Affy
10      KCNJ5              HGNC         3355876                   Affy
11      KCNJ5              HGNC      GO:0016020          Gene Ontology
12      KCNJ5              HGNC    ILMN_1772224               Illumina
13      KCNJ5              HGNC         3355875                   Affy
14      KCNJ5              HGNC      GO:0005886          Gene Ontology
15      KCNJ5              HGNC     11736490_at                   Affy
16      KCNJ5              HGNC        16733397                   Affy
17      KCNJ5              HGNC         3355879                   Affy
18      KCNJ5              HGNC      GO:0006811          Gene Ontology
19      KCNJ5              HGNC   11752646_a_at                   Affy
20      KCNJ5              HGNC      GO:0005244          Gene Ontology
21      KCNJ5              HGNC          P48544         Uniprot-TrEMBL
22      KCNJ5              HGNC  211817_PM_s_at                   Affy
23      KCNJ5              HGNC        91661_at                   Affy
24      KCNJ5              HGNC         3666238                   Affy

In [20]:
# Create mock dataframes
molmedb_data = {
    "identifier": ["KCNJ5", "SLC25A1"],
    "identifier.source": ["HGNC", "HGNC"],
    "target": ["P38398", "P38398"],
    "target.source": ["Uniprot-TrEMBL", "Uniprot-TrEMBL"],
    "MolMeDB_transporter_inhibitor": [[{
        "MolMeDB_compound_name": "Euphorbiaproliferin C",
        "MolMeDB_inchikey": "IYIKLHRQXLHMJQ-UHFFFAOYSA-N",
        "MolMeDB_smiles": "CC(=O)OC1C2(C)OCC3(C(=O)C=CC(C(C)(C)OC(C)=O)C23)C(OC(C)=O)C2C(OC(=O)C(C)C)C(C)CC21OC(C)=O",
        "MolMeDB_id": "MM470852",
        "source_pmid": "27441737"
    }], [{
        "MolMeDB_compound_name": "Euphorbiaproliferin C",
        "MolMeDB_inchikey": "XXROGKLTLUQVRX-UHFFFAOYSA-N",
        "MolMeDB_smiles": "CC(=O)OC1C2(C)OCC3(C(=O)C=CC(C(C)(C)OC(C)=O)C23)C(OC(C)=O)C2C(OC(=O)C(C)C)C(C)CC21OC(C)=O",
        "MolMeDB_id": "MM470852",
        "source_pmid": "27441737"
    }]]
}

molmedb_df = pd.DataFrame(molmedb_data)

opentargets_data = {
    "identifier": ["KCNJ5", "SLC25A1"],
    "identifier.source": ["HGNC", "HGNC"],
    "target": ["P38398", "P38398"],
    "target.source": ["Uniprot-TrEMBL", "Uniprot-TrEMBL"],
    "OpenTargets_gene_compounds": [[{
        "chembl_id": "CHEMBL:CHEMBL234926",
        "drugbank_id": None,
        "compound_cid": "CID:9930048",
        "compound_name": "VERNAKALANT HYDROCHLORIDE",
        "clincal_trial_phase": 4.0,
        "is_approved": True,
        "relation": "activates",
        "adverse_effect_count": 1.0,
        "adverse_effect": [{"name": "atrial flutter"}]
    }], [{
        "chembl_id": "CHEMBL:CHEMBL633",
        "drugbank_id": None,
        "compound_cid": "CID:9930048",
        "compound_name": "VERNAKALANT HYDROCHLORIDE",
        "clincal_trial_phase": 4.0,
        "is_approved": True,
        "relation": "activates",
        "adverse_effect_count": 1.0,
        "adverse_effect": [{"name": "atrial flutter"}]
    }]]
}

opentargets_df = pd.DataFrame(opentargets_data)

pubchem_data = {
    "identifier": ["KCNJ5", "SLC25A1"],
    "identifier.source": ["HGNC", "HGNC"],
    "target": ["P38398", "P38398"],
    "target.source": ["Uniprot-TrEMBL", "Uniprot-TrEMBL"],
    "PubChem_assays": [[{
        "pubchem_assay_id": "AID:504669",
        "assay_type": "IC50",
        "outcome": "active",
        "compound_cid": "CID:2157",
        "compound_name": "2-nitro-N-quinolin-8-ylbenzenesulfonamide",
        "smiles": "C1=CC=C(C(=C1)[N+](=O)[O-])S(=O)(=O)NC2=CC=CC3=C2N=CC=C3",
        "inchi": "InChI=1S/C15H11N3O4S/c19-18(20)13-8-1-2-9-14(13)23(21,22)17-12-7-3-5-11-6-4-10-16-15(11)12/h1-10,17H"
    }], [{
        "pubchem_assay_id": "AID:504669",
        "assay_type": "IC50",
        "outcome": "active",
        "compound_cid": "CID:7858",
        "compound_name": "2-nitro-N-quinolin-8-ylbenzenesulfonamide",
        "smiles": "C1=CC=C(C(=C1)[N+](=O)[O-])S(=O)(=O)NC2=CC=CC3=C2N=CC=C3",
        "inchi": "InChI=1S/C15H11N3O4S/c19-18(20)13-8-1-2-9-14(13)23(21,22)17-12-7-3-5-11-6-4-10-16-15(11)12/h1-10,17H"
    }]]
}

pubchem_df = pd.DataFrame(pubchem_data)

pubchem_df.head()

,identifier,identifier.source,target,target.source,PubChem_assays
0,KCNJ5,HGNC,P38398,Uniprot-TrEMBL,"[{'pubchem_assay_id': 'AID:504669', 'assay_typ..."
1,SLC25A1,HGNC,P38398,Uniprot-TrEMBL,"[{'pubchem_assay_id': 'AID:504669', 'assay_typ..."

In [27]:
combined_df = combine_sources(
    bridgedb_df,
    [
        pubchem_df, 
        opentargets_df,
    ],
)

In [28]:
combined_df, compoundwiki_metadata = compoundwiki.get_compound_annotations(combined_df)

b
c
Processing PubChem column for compounds: PubChem_assays
Processing OpenTargets column for compounds: OpenTargets_gene_compounds

In [23]:
combined_df.head()

,identifier,identifier.source,target,target.source,PubChem_assays
0,KCNJ5,HGNC,ENSG00000120457,Ensembl,"[{'pubchem_assay_id': 'AID:504669', 'assay_typ..."
1,SLC25A1,HGNC,ENSG00000100075,Ensembl,"[{'pubchem_assay_id': 'AID:504669', 'assay_typ..."

In [24]:
combined_df['PubChem_assays']

0    [{'pubchem_assay_id': 'AID:504669', 'assay_typ...
1    [{'pubchem_assay_id': 'AID:504669', 'assay_typ...
Name: PubChem_assays, dtype: object

In [29]:
pygraph = generator.build_networkx_graph(combined_df)

Building graph: 100%|██████████| 2/2 [00:00<00:00, 1237.81it/s]

In [30]:
from pyBiodatafuse.graph import cytoscape

cytoscape.load_graph(pygraph, network_name="Test network")

Applying default style...
Applying preferred layout